apiVersion: v1
kind: Service
metadata:
  name: playgraphqlseed
  labels:
    app: playgraphqlseed
spec:
  ports:
  - port: 80
    targetPort: 9000
    name: http
  selector:
    app: playgraphqlseed
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: playgraphqlseed
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: playgraphqlseed
    spec:
      containers:
      - name: app
        image: playgraphqlseed/playgraphqlseed:latest
        ports:
        - containerPort: 9000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: playgraphqlseed-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: playgraphqlseed.com
    http:
      paths:
      - backend:
          serviceName: playgraphqlseed
          servicePort: 9000
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: playgraphqlseed
  name: playgraphqlseed-config
data:
  application.conf: |
    foo = "bar"
---
